spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useSSL=false
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: create-drop
